import math
SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 600
TILE_SIZE = 64

MIN_SPEED = 0.1 #units in pixels per frame
MAX_SPEED = 3.0
PLAYER_SPEED = .2
BULLET_SPEED = .75

NUM_LIVES = 5
TURN_SPEED = .4

PLAYER_ANGLE = 0
PLAYER_ROTATION_SPEED = .8
